FROM node:24.14.0-alpine3.23@sha256:7fddd9ddeae8196abf4a3ef2de34e11f7b1a722119f91f28ddf1e99dcafdf114 AS builder

ARG TARGETARCH
ARG TARGETOS

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
RUN npm ci --ignore-scripts --production
COPY ./ .

RUN npm run build

FROM node:24.14.0-alpine3.23@sha256:7fddd9ddeae8196abf4a3ef2de34e11f7b1a722119f91f28ddf1e99dcafdf114 AS package

ARG CI_ENV=noci
ARG GIT_COMMIT=git_commit_undefined
ARG GIT_BRANCH=git_branch_undefined
ARG VERSION=not_versioned

WORKDIR /app

RUN addgroup -S apprunner && adduser -S apprunner -G apprunner && chown apprunner:apprunner -R /app

COPY --chown=apprunner:apprunner package*.json ./
COPY --from=builder --chown=apprunner:apprunner /app/dist ./

USER apprunner

RUN npm ci --ignore-scripts --production

ENV APPDIR=/app


ENV PORT 4000
ENV NODE_OPTIONS="--max-old-space-size=8192"
EXPOSE 4000 2222
ENTRYPOINT ["sh"]
# ENTRYPOINT ["node", "./bin/www"]
